# Generated by Django 5.0.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, db_column='coverImage', max_length=500, null=True)),
                ('blocks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_meta', models.JSONField(blank=True, db_column='seoMeta', null=True)),
                ('is_featured', models.BooleanField(db_column='isFeatured', default=False)),
                ('reading_time', models.IntegerField(db_column='readingTime', default=0)),
                ('view_count', models.IntegerField(db_column='viewCount', default=0)),
                ('published_at', models.DateTimeField(blank=True, db_column='publishedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('author', models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
