# Generated by Django 5.0.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('generate_image', 'Generate Image'), ('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('chat', 'Chat'), ('chat_stream', 'Chat Stream'), ('api_chat', 'API Chat'), ('api_chat_stream', 'API Chat Stream'), ('api_image_generation', 'API Image Generation'), ('convert_word_to_pdf', 'Convert Word to PDF'), ('convert_pdf_to_word', 'Convert PDF to Word'), ('document_conversion', 'Document Conversion'), ('google_login', 'Google Login')], max_length=50)),
                ('credits_used', models.DecimalField(db_column='creditsUsed', decimal_places=4, default=0, max_digits=10)),
                ('cost_usd', models.DecimalField(db_column='costUsd', decimal_places=4, default=0, max_digits=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
