# Generated by Django 5.0.1 on 2026-01-21 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('credits_used', models.DecimalField(db_column='creditsUsed', decimal_places=4, default=0, max_digits=10)),
                ('total_spent_usd', models.DecimalField(db_column='totalSpentUsd', decimal_places=4, default=0, max_digits=10)),
                ('token_balance', models.BigIntegerField(db_column='tokenBalance', default=0)),
                ('is_pro', models.BooleanField(db_column='isPro', default=False)),
                ('pro_expires_at', models.DateTimeField(blank=True, db_column='proExpiresAt', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('is_email_verified', models.BooleanField(db_column='isEmailVerified', default=False)),
                ('google_id', models.CharField(blank=True, db_column='googleId', max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, db_column='avatarUrl', max_length=500, null=True)),
                ('has_received_welcome_bonus', models.BooleanField(db_column='hasReceivedWelcomeBonus', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
