"""
Workflow API - creates workflows in n8n via REST API.
"""

import httpx
from django.conf import settings
from django.http import HttpRequest
from ninja import Router
from ninja.errors import HttpError

from utils.auth import AuthBearer, get_current_user
from .schemas import CreateWorkflowIn, WorkflowOut

router = Router(auth=AuthBearer())


def get_n8n_config():
    """Get n8n configuration from settings."""
    return {
        "url": getattr(settings, "N8N_URL", "http://localhost:5678"),
        "api_key": getattr(settings, "N8N_API_KEY", ""),
    }


@router.post("/create", response=WorkflowOut)
async def create_workflow(request: HttpRequest, data: CreateWorkflowIn):
    """
    Create a workflow in n8n.

    Receives workflow JSON from frontend (generated by AI),
    calls n8n REST API to create the workflow,
    returns workflow URL for iframe display.
    """
    user = get_current_user(request)
    config = get_n8n_config()

    if not config["api_key"]:
        return WorkflowOut(
            success=False,
            error="N8N API key not configured"
        )

    # Validate and normalize workflow
    workflow = data.workflow.copy()

    # Add default name if missing
    if not workflow.get("name"):
        workflow["name"] = "AI Generated Workflow"

    # Add default settings if missing (required by n8n API)
    if not workflow.get("settings"):
        workflow["settings"] = {
            "executionOrder": "v1"
        }

    # Add empty connections if missing
    if not workflow.get("connections"):
        workflow["connections"] = {}

    # Validate nodes exist
    if not workflow.get("nodes"):
        return WorkflowOut(
            success=False,
            error="Workflow must have at least one node"
        )

    # Ensure each node has required fields
    for i, node in enumerate(workflow["nodes"]):
        if not node.get("id"):
            node["id"] = str(i + 1)
        if not node.get("position"):
            node["position"] = [250 + (i * 200), 300]
        if not node.get("typeVersion"):
            node["typeVersion"] = 1
        if not node.get("parameters"):
            node["parameters"] = {}

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{config['url']}/api/v1/workflows",
                headers={
                    "X-N8N-API-KEY": config["api_key"],
                    "Content-Type": "application/json",
                },
                json=workflow,
                timeout=30.0,
            )

        if response.status_code == 200 or response.status_code == 201:
            result = response.json()
            workflow_id = result.get("id")

            return WorkflowOut(
                success=True,
                workflowId=workflow_id,
                workflowUrl=f"{config['url']}/workflow/{workflow_id}"
            )
        else:
            error_text = response.text
            return WorkflowOut(
                success=False,
                error=f"n8n API error: {error_text}"
            )

    except httpx.TimeoutException:
        return WorkflowOut(
            success=False,
            error="Connection to n8n timed out"
        )
    except httpx.ConnectError:
        return WorkflowOut(
            success=False,
            error="Cannot connect to n8n. Make sure n8n is running."
        )
    except Exception as e:
        return WorkflowOut(
            success=False,
            error=str(e)
        )


@router.get("/config")
def get_workflow_config(request: HttpRequest):
    """
    Get n8n configuration for frontend.

    Returns the n8n URL so frontend can display iframe.
    """
    config = get_n8n_config()

    return {
        "n8nUrl": config["url"],
        "configured": bool(config["api_key"])
    }
